### ISSUE TITLE
Add Rchain Rhoc

### ISSUE THREAD

**Issue by bdresser** [MetaMask/eth-contract-metadata#100]
as per MetaMask/metamask-extension#4008

**Comment by estebanmino** [comment]
@bdresser where is the PR or information for this?

**Comment by bdresser** [comment]
@estebanmino I just moved an open issue on the extension to this repo. I believe @kumavis originally filed it to add the RHOC token to our list (https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5)

**Comment by estebanmino** [comment]
Ok, I couldn't find the token in the list so I'll create a PR

**Comment by estebanmino** [comment]
Done, waiting for review.
