### ISSUE TITLE
Add BANKEX Project Utility Token

### ISSUE THREAD

**Issue by efugenni** [MetaMask/eth-contract-metadata#206]
Etherscan: https://etherscan.io/token/0x45245bc59219eeaaf6cd3f382e078a461ff9de7b
Project website: https://bankex.com/
Twitter: https://twitter.com/BANKEX
Facebook: https://www.facebook.com/BankExchange/
Reddit: https://www.reddit.com/r/bankex/
Telegram: https://t.me/bankex
Github: https://github.com/BankEx
![bankex_logo](https://user-images.githubusercontent.com/45557770/49365856-e7700280-f6f8-11e8-8587-f1fd3fe89f91.png)

**Comment by estebanmino** [comment]
Hi @efugenni, please submit a PR with this. Thanks!
