### ISSUE TITLE
Outdated npm package

### ISSUE THREAD

**Issue by corollari** [MetaMask/eth-contract-metadata#212]
A number of new contracts have been added to the list since the npm package was last updated (6 months ago), which results in outdated lists being used for all the software that depends on that npm module.
If automating the package updating process is not a viable option, a possibility could be to tell people to add this git repository as a submodule to their project, so the list will be kept updated.

**Comment by estebanmino** [comment]
Hi @corollari thanks for pointing this out! Just bumped the package to version 1.9.0, thanks!
