### ISSUE TITLE
Images for recently added tokens not appearing in MetaMask

### ISSUE THREAD

**Issue by joshfraser** [MetaMask/eth-contract-metadata#273]
While the latest contract-map.json file is being fetched by the MetaMask Chrome extension (in background.js), the images for all the recently added tokens are not being included. The last one that worked was STAR, but all the recent additions to this list are missing their associated images and are not showing up in MetaMask.

Here are the tokens that are not showing up in MetaMask despite being included in contract-map.json:
GROO, SAN, LPT, HOT, ENJ, ELF, WAX, POWR, XBP, KODA, OGN, REQ, BETHER

**Comment by estebanmino** [comment]
Thanks for reporting @joshfraser! Fixed in https://github.com/MetaMask/metamask-extension/pull/6396
