### ISSUE TITLE
Migrating MLN token

### ISSUE THREAD

**Issue by perhamgirl** [MetaMask/eth-contract-metadata#326]
Hi there,

I just wanted to check if you are aware that we migrated MLN to a new token contract a couple of months ago. I am unable to see my MLN balance in my Metamask wallet and I assume that is because you are still reading the old contract balance. The announcement of the Migration event is here https://medium.com/melonprotocol/mln-token-migration-event-96b1c8003876 and the instructions were written up here https://medium.com/melonprotocol/mln-token-migration-instructions-196a645fc3ac

Also, I noticed that the logo you are using for the token is actually the company logo (Melonport) and it would be great to update the logo to the protocol logo which can be downloaded here https://github.com/melonproject/branding/blob/master/melon/12_Melon_logo_transparent.png.

**Comment by jennazenk** [comment]
up :)

**Comment by fubhy** [comment]
I created a pull request with the new information: https://github.com/MetaMask/eth-contract-metadata/pull/396
