### ISSUE TITLE
MKR precision is incorrect

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/eth-contract-metadata#5]
MKR has 18 decimals, [not 0](https://github.com/MetaMask/eth-contract-metadata/blob/master/contract-map.json#L140).

Apparently 18 is pretty common & standard, which makes me nervous about the number of tokens we have listed as `0` decimals.

Any guesses of how many of the other `0` decimal tokens might be incorrectly marked, @mintheredonethat?

**Comment by mintheredonethat** [comment]
I pulled the metadata straight from etherscan - let me look for other sources & correct them accordingly
