### ISSUE TITLE
Add WETH support

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/eth-contract-metadata#73]
Wrapped-ether is used in many projects, we should represent it. Needs a special logo.

**Comment by tomhschmidt** [comment]
Hey @danfinlay -- our designer (Ben Burns) is down to make a WETH logo and make a PR for the token if you're interested

**Comment by danfinlay** [comment]
I’d merge that!

**Comment by estebanmino** [comment]
added on https://github.com/MetaMask/eth-contract-metadata/pull/94
